from structure.structure_memory import StructureMemory
from structure.structure_realisation import StructureRealisation
from structure.structure_top import StructureTop

from structure.drawers import StructColorator, draw_realisation_on_ax